version: "3.3"

services:
  db-server:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "findme"

  web:
    ports:
      - 3000:3000
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    working_dir: /usr/src/web
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
      - /usr/src/web/.next
    depends_on:
      - db-server

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/usr/src/api
      - "/usr/src/api/node_modules"
    environment:
      API_SECRET: "segredoaleatorio"
      MAIL_HOST: "smtp.postmarkapp.com"
      MAIL_PORT: "2525"
    ports:
      - "3333:3333"
    working_dir: /usr/src/api
    depends_on:
      - db-server
