version: "3.3"

services:
  db-server:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "findme"

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    working_dir: /usr/src/web
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
      - /usr/src/web/.next
    ports:
      - 3000:3000
    depends_on:
      - db-server

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/usr/src/api
      - "/usr/src/api/node_modules"
      - "/usr/src/api/dist"
    working_dir: /usr/src/api
    ports:
      - 3333:3333
    depends_on:
      - db-server
