version: "3.3"

services:
  web:
    ports:
      - 3000:3000
    build:
      context: ./web
      dockerfile: Dockerfile
    working_dir: /usr/src/web
    volumes:
      - ./web:/usr/src/web
      - /usr/src/web/node_modules
      - /usr/src/web/.next
